### ISSUE TITLE
epi-commerce-empty template could not be run

### ISSUE THREAD

**Issue by cuong0993** [episerver/content-templates#44]
epi-commerce-empty template from the latest EPiServer.Templates 1.4.0 could not be run after creation.

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMOBDO2AER8B", Request id "0HMOBDO2AER8B:00000001": An unhandled exception was thrown by the application.
      EPiServer.Core.EPiServerException: There are incomplete migration steps. The site can be in unstable state. Please navigate to front-end site and complete remaining migration steps, then restart Commerce Manager site. If you see this message on the front-end site, it means no Catalog Content models (decorated with the CatalogContentType attribute) were found. Add a Catalog Content type, or set the appSetting 'episerver:SkipCatalogContentModelCheck' to true to bypass this check. Warning! Bypassing this  check in the Commerce Manager site or other application which does not have the content model types available could lead to data loss!
         at EPiServer.Commerce.Internal.Migration.RedirectingRequest.InitializeAsync()
         at EPiServer.Middleware.InitializeOnFirstRequestMiddleware.StartFirstInitializers(HttpContext httpContext)
         at EPiServer.Middleware.InitializeOnFirstRequestMiddleware.InvokeAsync(HttpContext httpContext)
         at EPiServer.Framework.DependencyInjection.Internal.VisitorGroupMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.WebTools.BrowserLink.Net.BrowserLinkMiddleware.ExecuteWithFilterAsync(IHttpSocketAdapter injectScriptSocket, String requestId, HttpContext httpContext)
         at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

![image](https://user-images.githubusercontent.com/8237154/218109276-1f73a904-2988-4eaa-8a73-e10d0034066f.png)

**Comment by KennethHoff** [comment]
@cuong0993 how did you solve this? Do you remember?

**Comment by cuong0993** [comment]
@KennethHoff
I did like this https://eric.st-pierre.xyz/posts/move-net5-optimizely-sites/
